import pandas as pd

ticker_to_names = {
    'AAPL': 'Apple Inc.',
    'ABBV': 'AbbVie Inc.',
    'ADBE': 'Adobe Inc.',
    'AMZN': 'Amazon.com Inc.',
    'AVGO': 'Broadcom Inc.',
    'BA': 'Boeing Co.',
    'BAC': 'Bank of America Corp.',
    'BTC-USD': 'Bitcoin',
    'CAT': 'Caterpillar Inc.',
    'CMCSA': 'Comcast Corp.',
    'COST': 'Costco Wholesale Corp.',
    'CRM': 'Salesforce Inc.',
    'CSCO': 'Cisco Systems Inc.',
    'CVX': 'Chevron Corp.',
    'DHR': 'Danaher Corp.',
    'DIA': 'SPDR Dow Jones Industrial Average ETF',
    'DIS': 'The Walt Disney Company',
    'GE': 'General Electric Co.',
    'GLD': 'SPDR Gold Shares',
    'GOOGL': 'Alphabet Inc. (Class A)',
    'GS': 'Goldman Sachs Group Inc.',
    'HD': 'Home Depot Inc.',
    'IEF': 'iShares 7-10 Year Treasury Bond ETF',
    'JNJ': 'Johnson & Johnson',
    'JPM': 'JPMorgan Chase & Co.',
    'KO': 'Coca-Cola Co.',
    'LLY': 'Eli Lilly and Co.',
    'LTC-USD': 'Litecoin',
    'MA': 'Mastercard Inc.',
    'META': 'Meta Platforms Inc.',
    'MRK': 'Merck & Co. Inc.',
    'MS': 'Morgan Stanley',
    'MSFT': 'Microsoft Corp.',
    'NFLX': 'Netflix Inc.',
    'NKE': 'Nike Inc.',
    'NVDA': 'NVIDIA Corp.',
    'PEP': 'PepsiCo Inc.',
    'PFE': 'Pfizer Inc.',
    'PG': 'Procter & Gamble Co.',
    'QQQ': 'Invesco QQQ Trust',
    'SLV': 'iShares Silver Trust',
    'SPY': 'SPDR S&P 500 ETF Trust',
    'TLT': 'iShares 20+ Year Treasury Bond ETF',
    'TMO': 'Thermo Fisher Scientific Inc.',
    'TMUS': 'T-Mobile US Inc.',
    'TSLA': 'Tesla Inc.',
    'TXN': 'Texas Instruments Inc.',
    'UNH': 'UnitedHealth Group Inc.',
    'V': 'Visa Inc.',
    'VZ': 'Verizon Communications Inc.',
    'WFC': 'Wells Fargo & Co.',
    'WMT': 'Walmart Inc.',
    'XOM': 'Exxon Mobil Corp.'
}

names_to_ticker = {
    'Apple Inc.': 'AAPL',
    'AbbVie Inc.': 'ABBV',
    'Adobe Inc.': 'ADBE',
    'Amazon.com Inc.': 'AMZN',
    'Broadcom Inc.': 'AVGO',
    'Boeing Co.': 'BA',
    'Bank of America Corp.': 'BAC',
    'Bitcoin': 'BTC-USD',
    'Caterpillar Inc.': 'CAT',
    'Comcast Corp.': 'CMCSA',
    'Costco Wholesale Corp.': 'COST',
    'Salesforce Inc.': 'CRM',
    'Cisco Systems Inc.': 'CSCO',
    'Chevron Corp.': 'CVX',
    'Danaher Corp.': 'DHR',
    'SPDR Dow Jones Industrial Average ETF': 'DIA',
    'The Walt Disney Company': 'DIS',
    'General Electric Co.': 'GE',
    'SPDR Gold Shares': 'GLD',
    'Alphabet Inc. (Class A)': 'GOOGL',
    'Goldman Sachs Group Inc.': 'GS',
    'Home Depot Inc.': 'HD',
    'iShares 7-10 Year Treasury Bond ETF': 'IEF',
    'Johnson & Johnson': 'JNJ',
    'JPMorgan Chase & Co.': 'JPM',
    'Coca-Cola Co.': 'KO',
    'Eli Lilly and Co.': 'LLY',
    'Litecoin': 'LTC-USD',
    'Mastercard Inc.': 'MA',
    'Meta Platforms Inc.': 'META',
    'Merck & Co. Inc.': 'MRK',
    'Morgan Stanley': 'MS',
    'Microsoft Corp.': 'MSFT',
    'Netflix Inc.': 'NFLX',
    'Nike Inc.': 'NKE',
    'NVIDIA Corp.': 'NVDA',
    'PepsiCo Inc.': 'PEP',
    'Pfizer Inc.': 'PFE',
    'Procter & Gamble Co.': 'PG',
    'Invesco QQQ Trust': 'QQQ',
    'iShares Silver Trust': 'SLV',
    'SPDR S&P 500 ETF Trust': 'SPY',
    'iShares 20+ Year Treasury Bond ETF': 'TLT',
    'Thermo Fisher Scientific Inc.': 'TMO',
    'T-Mobile US Inc.': 'TMUS',
    'Tesla Inc.': 'TSLA',
    'Texas Instruments Inc.': 'TXN',
    'UnitedHealth Group Inc.': 'UNH',
    'Visa Inc.': 'V',
    'Verizon Communications Inc.': 'VZ',
    'Wells Fargo & Co.': 'WFC',
    'Walmart Inc.': 'WMT',
    'Exxon Mobil Corp.': 'XOM'
}

def adjust_to_last_friday(date):
    weekday = date.weekday()
    if weekday == 5:
        return date - pd.Timedelta(days=1)
    elif weekday == 6:
        return date - pd.Timedelta(days=2)
    return date